language: php

sudo: required
dist: trusty

matrix:
    include:
        - php: 5.6.25
        - php: 7.0
        - php: hhvm
          group: edge
    fast_finish: true

before_script:
    - composer install

script:
    - vendor/bin/phpunit
    - vendor/bin/phpcs --standard=PSR2 src/

after_success:
    - bash <(curl -s https://codecov.io/bash)
